Repository arcalos-environments/environment-hornberyl-dev, pull requests merged in 2019-11, with the labels that each got.

#10 fix: add non-basic auth ingress for boot tenant service access
  env/templates/701-boot-tenant-service-ing.yaml
  jx-requirements.yml
Labels: approved, size/M

#12 feat: upgrade from Playground to Staging
  dependency-matrix/matrix.md
  env/arcalosui/values.tmpl.yaml
  env/jx-app-sso/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/boot-cj.yaml
  env/templates/upgrade-cj.yaml
  env/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, size/L

#13 chore(deps): bump jx-tenant-service from 0.0.174 to 0.0.237
  env/requirements.yaml
  jenkins-x.yml
  jx-requirements.yml
Labels: approved, size/S

#14 feat: promote latest jenkins x tenant, github app + lighthouse and UI…
  env/lighthouse-githubapp/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-lighthouse-githubapp-ingress.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
Labels: approved, lgtm, size/M

#15 fix: boot upgrade job and aligm with Play environment
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#16 feat: segment keys are required
  .secrets.baseline
  env/jxui-arcalos/values.tmpl.yaml
  env/templates/arcalos-secret.yaml
  env/templates/boot-cj.yaml
  env/values.tmpl.yaml
  jenkins-x.yml
  jx-requirements.yml
Labels: approved, size/M

#17 feat: promote latest release changes from Play to Staging
  env/controllerbuild/values.yaml
  env/jx-tenant-service/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
  env/requirements.yaml
  env/templates/upgrade-cj.yaml
Labels: approved, lgtm, size/S

#18 fix: use staging bot username
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, size/XS

#19 chore: promote from Play
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/S

#20 chore: promote changes from Play to Staging
  env/requirements.yaml
Labels: approved, size/XS
