Repository arcalos-environments/environment-hornberyl-dev, pull requests merged in 2019-10, with the labels that each got.

#2 feat: promote latest tenant service and arcalos ui
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-jx-tenant-service-ing.yaml
  env/values.tmpl.yaml
  jenkins-x.yml
Labels: approved, size/S

#4 chore: migrate to staging-jxaas.live
  env/parameters.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#3 Dashboard
  env/arcalosui/values.tmpl.yaml
  env/jx-app-sso/values.tmpl.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
Labels: approved, lgtm, size/L

#5 Fix: remove dot and dash
  jx-requirements.yml
  systems/acme/values.tmpl.yaml
Labels: approved, size/XS

#7 fix: PR builds as we're not quite using this yet
  jx-requirements.yml
Labels: approved, size/XS

#6 feat: upgrade tenant service and create tenants in dedicated GCP folder
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#8 chore: switch to cloudbees sso
  env/jx-app-sso/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#9 chore: jx-tenant-service to 0.0.145
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, size/XS
