Repository arcalos-environments/environment-hornberyl-dev, pull requests merged in 2019-12, with the labels that each got.

#21 chore: promote TS and LHGH from Playground to Staging
  env/requirements.yaml
Labels: approved, size/XS

#22 chore: promote lighthouse-githubapp with fix to using the right GHA…
  env/requirements.yaml
Labels: approved, size/XS

#23 chore: promote lighthouse-githubapp with fix to using the right GHA…
  env/requirements.yaml
Labels: approved, size/XS

#24 fix: promotions uasing the right gcr.io
  env/requirements.yaml
Labels: approved, size/XS

#25 fix: upgrade the UI
  env/requirements.yaml
Labels: approved, size/XS

#26 improvement: install jx-app-datadog
  env/jx-app-datadog/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#27 fix: upgrade UI
  env/requirements.yaml
Labels: approved, size/XS

#28 chore: promote latest changes from Play to Staging
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#29 chore: promote from Play - includes new users
  env/requirements.yaml
Labels: approved, size/XS

#30 feat: update boot-tenant-service ingress
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#31 fix: upgrade versions
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#32 fix: upgrade lighthouse
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#33 fix: upgrade tenant service
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#35 fix: upgrade version stream, arcalos tag, TS and LH versions
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#36 chore: lock the template down to cloudbees-poc-it-0.0.622
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#34 chore: attempt a custom scheduler for the arcalos repo
  env/templates/arcalos-scheduler.yaml
  repositories/templates/cloudbees-arcalos.yaml
Labels: approved, lgtm, size/M

#37 chore(deps): bump jx-tenant-service from 0.0.319 to 0.0.320
  env/requirements.yaml
Labels: size/XS

#38 chore(deps): bump jx-tenant-service from 0.0.320 to 0.0.323
  env/requirements.yaml
Labels: size/XS

#39 chore(deps): bump jx-tenant-service from 0.0.323 to 0.0.325
  env/requirements.yaml
Labels: size/XS

#40 Revert "chore(deps): bump jx-tenant-service from 0.0.323 to 0.0.325"
  env/requirements.yaml
Labels: size/XS

#41 chore(deps): bump jx-tenant-service from 0.0.323 to 0.0.325
  env/requirements.yaml
Labels: size/XS

#42 improvement: adds tag clustername
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#43 chore: using 0.0.632 as the latest instance template
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#44 chore(deps): bump jx-tenant-service from 0.0.325 to 0.0.332
  env/requirements.yaml
Labels: size/XS

#45 chore(deps): bump jx-tenant-service from 0.0.332 to 0.0.342
  env/requirements.yaml
Labels: size/XS

#46 chore: fail missing/invalid signature
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS
