Repository arcalos-environments/environment-hornberyl-dev, pull requests merged in 2020-03, with the labels that each got.

#74 chore: added arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#75 chore: update apps inline with raccoon
  env/jx-production/000-namespace.yaml
  env/jx-staging/000-namespace.yaml
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
  env/templates/000-namespace.yaml
  env/templates/upgrade-cj.yaml
Labels: approved, lgtm, size/S

#76 chore: corrected secret name to arcalos-alpha-prod-secret
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#109 fix: change arcalos producer sa secret key name
  env/jx-tenant-service/values.tmpl.yaml
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#113 chore: update staging to use aps alpha environment
  env/jx-tenant-service/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/S

#135 fix: update jxui-backend service account
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#134 chore: remove domain_issuer_url from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#141 chore: updateController regional location
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#136 chore: removed unrequired values from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#137 chore: remove unrequired values from arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#140 chore: lock staging environment to v0.0.955
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#156 fix: added cjxd-bot to OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#168 chore: pass the variable for the github app installation link
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#177 chore: allow hmac api in ing
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#315 Revert "chore(deps): bump https://github.com/cloudbees/jxui-frontend from 0.0.1156 to 0.0.1164"
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  env/requirements.yaml
Labels: approved, size/XS

#317 feat: use oauth2_proxy for dashboard auth flows
  env/jx-app-sso/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
Labels: approved, lgtm, size/L

#331 feat: redirect / to /jenkinsx
  env/templates/700-jxui-backend-ing.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/M

#340 chore: allow staging to use the latest templates for now
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#343 chore: update staging url for GHA
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#356 feat: use latest datadog agent and log arcalos build pods
  env/jx-app-datadog/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S
