Repository arcalos-environments/environment-hornberyl-dev, pull requests merged in 2020-04, with the labels that each got.

#393 Revert "chore(deps): bump https://github.com/cloudbees/jxui-frontend from 0.0.1184 to 0.0.1185"
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  env/requirements.yaml
Labels: size/XS

#433 fix: specify correct values for datadog app
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/S

#438 fix: attempt to remove the use if custom oauth2 image
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/S

#439 chore: allow update workspace endpoint in ing
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#534 chore: add variable to show GHA name to install
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#577 fix: create the datadog secret
  env/templates/datadog-dogrc-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#633 chore: rox jx-tenant-service apiKey
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS
